### ISSUE TITLE
Spam clicking Shuffle enables a sound without showing it's active

### ISSUE THREAD

**Issue by vetkaashaas** [DEATHTINYZ/moodlody#1]
If you spam click the shuffle button 10+ times quickly, it seems that some sounds are enabled (and playing) without the sound's tile displaying the sliderbar (displaying as active)

**Comment by DEATHTINYZ** [comment]
> If you spam click the shuffle button 10+ times quickly, it seems that some sounds are enabled (and playing) without the sound's tile displaying the sliderbar (displaying as active)

Ok, I see the problem, thanks.
